In [3]:
import pandas as pd

df_qol = pd.read_csv('data/quality_of_life_indices_by_country.csv')

In [16]:
df_qol['Year'] = df_qol['Year'].astype(str).str.replace(r'/2$', '', regex=True)
df_qol = df_qol.groupby(['Country', 'Year'], as_index=False, sort=False).mean(numeric_only=True)

In [20]:
df_qol

,Country,Year,Rank,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index
0,Switzerland,2014,1.0,207.35,137.55,70.00,68.00,143.20,7.05,25.15,26.40,NaN
1,Germany,2014,2.0,189.65,109.05,71.90,76.00,86.95,5.85,33.75,30.25,NaN
2,Sweden,2014,3.5,178.75,104.00,59.85,76.15,101.10,9.55,33.25,17.35,NaN
3,Finland,2014,3.5,180.75,97.25,70.80,68.85,102.65,7.50,34.25,16.35,NaN
4,Denmark,2014,5.0,172.10,96.15,71.80,84.10,115.00,6.15,26.90,36.20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
442,Serbia,2026,33.0,127.60,64.70,63.00,52.10,42.60,14.80,30.60,65.80,82.7
443,North Macedonia,2026,34.0,124.20,66.10,58.60,55.40,35.50,11.80,24.30,79.20,79.9
444,Ukraine,2026,35.0,117.10,51.10,53.10,55.80,28.20,12.80,37.80,62.20,71.3
445,Russia,2026,36.0,115.60,63.20,61.80,61.60,36.50,13.70,43.30,58.40,38.0
446,Albania,2026,37.0,105.60,46.70,55.90,48.10,45.80,15.10,36.00,77.10,86.3

In [38]:
df_wdi = pd.read_excel('data/wdi.xlsx')

In [40]:
df_wdi.drop(range(148,153), inplace=True)

In [44]:
df_wdi = df_wdi.drop(columns=['Series Code'])

In [69]:
df_wdi1 = pd.DataFrame({"Country Name": [], "Country Code": [],"Year":[], "School enrollment, primary (%gross)": [], "Individuals using the internet (% of population)": [], "GDP per capita, PPP (current international $)": []})

In [29]:
import country_converter as cc

In [30]:
df_qol['Country Code'] = cc.convert(names=df_qol['Country'], to='ISO3')

In [76]:
df_qol["Year"] = df_qol["Year"].astype(int)

In [31]:
df_whr = pd.read_excel('data/WHR26_Data_Figure_2.1.xlsx')

In [32]:
df_whr.head()

,Year,Rank,Country name,Life evaluation (3-year average),Lower whisker,Upper whisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,2025,1,Finland,7.764,7.690,7.837,1.915,1.638,0.939,1.105,0.093,0.491,1.582
1,2025,2,Iceland,7.540,7.449,7.630,1.971,1.720,0.996,1.105,0.187,0.187,1.373
2,2025,3,Denmark,7.539,7.446,7.631,1.986,1.633,0.930,1.081,0.125,0.474,1.310
3,2025,4,Costa Rica,7.439,7.356,7.522,1.697,1.483,0.739,1.101,0.059,0.122,2.236
4,2025,5,Sweden,7.255,7.172,7.337,1.950,1.570,1.027,1.070,0.149,0.447,1.041

In [34]:
df_whr['Country Code'] = cc.convert(names=df_whr['Country name'], to='ISO3')

In [35]:
df_whr = df_whr[df_whr['Country Code'].isin(df_qol['Country Code'])]

In [79]:
atributi = [
    "Year",
    "Country Code",
    'Country name', 
    'Life evaluation (3-year average)', 
    'Explained by: Log GDP per capita', 
    'Explained by: Social support', 
    'Explained by: Healthy life expectancy', 
    'Explained by: Freedom to make life choices', 
    'Explained by: Generosity', 
    'Explained by: Perceptions of corruption',
    'Dystopia + residual'
]

skupno = pd.merge(df_qol, df_whr[atributi], on=["Year", "Country Code"], how="inner")

In [81]:
skupno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 22 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     406 non-null    object
 1   Year                                        406 non-null    int64
 2   Rank                                        406 non-null    float64
 3   Quality of Life Index                       406 non-null    float64
 4   Purchasing Power Index                      406 non-null    float64
 5   Safety Index                                406 non-null    float64
 6   Health Care Index                           406 non-null    float64
 7   Cost of Living Index                        406 non-null    float64
 8   Property Price to Income Ratio              406 non-null    float64
 9   Traffic Commute Time Index                  406 non-null    float64
 10  Pollution Index                             406 non-null    float64
 11  Climate Index                               341 non-null    float64
 12  Country Code                                406 non-null    object
 13  Country name                                406 non-null    object
 14  Life evaluation (3-year average)            406 non-null    float64
 15  Explained by: Log GDP per capita            245 non-null    float64
 16  Explained by: Social support                245 non-null    float64
 17  Explained by: Healthy life expectancy       245 non-null    float64
 18  Explained by: Freedom to make life choices  245 non-null    float64
 19  Explained by: Generosity                    245 non-null    float64
 20  Explained by: Perceptions of corruption     245 non-null    float64
 21  Dystopia + residual                         245 non-null    float64
dtypes: float64(18), int64(1), object(3)
memory usage: 69.9+ KB

In [82]:
skupno.drop(columns=['Country name'], inplace=True)

In [93]:
skupno = skupno[['Country', 'Country Code', 'Year', 'Rank', 'Quality of Life Index',
       'Purchasing Power Index', 'Safety Index', 'Health Care Index',
       'Cost of Living Index', 'Property Price to Income Ratio',
       'Traffic Commute Time Index', 'Pollution Index', 'Climate Index',
       'Life evaluation (3-year average)',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual']]

In [94]:
skupno.head()

,Country,Country Code,Year,Rank,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,...,Pollution Index,Climate Index,Life evaluation (3-year average),Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Switzerland,CHE,2014,1.0,207.35,137.55,70.00,68.00,143.20,7.05,...,26.40,NaN,7.587,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Germany,DEU,2014,2.0,189.65,109.05,71.90,76.00,86.95,5.85,...,30.25,NaN,6.750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sweden,SWE,2014,3.5,178.75,104.00,59.85,76.15,101.10,9.55,...,17.35,NaN,7.364,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Finland,FIN,2014,3.5,180.75,97.25,70.80,68.85,102.65,7.50,...,16.35,NaN,7.406,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Denmark,DNK,2014,5.0,172.10,96.15,71.80,84.10,115.00,6.15,...,36.20,NaN,7.527,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
df_hdi = pd.read_csv('data/HDR25_Composite_indices_complete_time_series.csv', encoding='Windows-1250')

In [104]:
df_hdi = df_hdi[df_hdi['iso3'].isin(df_qol['Country Code'])]

In [106]:
df_hdi.drop(columns=['country', 'region'], inplace=True)

C:\Users\borKa\AppData\Local\Temp\ipykernel_23964\1827759939.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hdi.drop(columns=['country', 'region'], inplace=True)

In [107]:
df_hdi.head()

,iso3,hdicode,hdi_rank_2023,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,hdi_1995,hdi_1996,...,pop_total_2014,pop_total_2015,pop_total_2016,pop_total_2017,pop_total_2018,pop_total_2019,pop_total_2020,pop_total_2021,pop_total_2022,pop_total_2023
1,ALB,Very High,71.0,0.654,0.638,0.622,0.624,0.629,0.638,0.647,...,2.903749,2.898632,2.897867,2.898242,2.894231,2.885009,2.871954,2.849636,2.827608,2.811655
9,AUT,Very High,22.0,0.832,0.835,0.841,0.845,0.851,0.856,0.861,...,8.547818,8.644039,8.737915,8.798777,8.841651,8.880876,8.921405,8.967056,9.064677,9.130429
15,BLR,Very High,65.0,NaN,NaN,NaN,NaN,NaN,0.692,0.697,...,9.472708,9.487293,9.499064,9.495790,9.480031,9.435420,9.350944,9.251365,9.173237,9.115680
16,BEL,Very High,10.0,0.824,0.829,0.845,0.860,0.868,0.875,0.881,...,11.210119,11.275334,11.332700,11.376580,11.428605,11.490618,11.540107,11.570844,11.641820,11.712893
21,BIH,Very High,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.564829,3.518540,3.473003,3.428682,3.387000,3.345533,3.299349,3.244908,3.204802,3.185073

In [109]:
df_hdi = df_hdi.loc[:, ~df_hdi.columns.str.contains(r'^\d{4}$') | df_hdi.columns.str.contains(r'(201[4-9]|202[0-5])')]
df_hdi = df_hdi.loc[:, df_hdi.columns.isin(['iso3']) | df_hdi.columns.str.contains(r'(201[4-9]|202[0-5])')]

C:\Users\borKa\AppData\Local\Temp\ipykernel_23964\3039077932.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_hdi = df_hdi.loc[:, ~df_hdi.columns.str.contains(r'^\d{4}$') | df_hdi.columns.str.contains(r'(201[4-9]|202[0-5])')]
C:\Users\borKa\AppData\Local\Temp\ipykernel_23964\3039077932.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_hdi = df_hdi.loc[:, df_hdi.columns.isin(['iso3']) | df_hdi.columns.str.contains(r'(201[4-9]|202[0-5])')]

In [120]:
df_hdi

,iso3,hdi_rank_2023,hdi_2014,hdi_2015,hdi_2016,hdi_2017,hdi_2018,hdi_2019,hdi_2020,hdi_2021,...,pop_total_2014,pop_total_2015,pop_total_2016,pop_total_2017,pop_total_2018,pop_total_2019,pop_total_2020,pop_total_2021,pop_total_2022,pop_total_2023
1,ALB,71.0,0.797,0.797,0.797,0.798,0.801,0.805,0.794,0.794,...,2.903749,2.898632,2.897867,2.898242,2.894231,2.885009,2.871954,2.849636,2.827608,2.811655
9,AUT,22.0,0.919,0.919,0.921,0.922,0.925,0.928,0.925,0.930,...,8.547818,8.644039,8.737915,8.798777,8.841651,8.880876,8.921405,8.967056,9.064677,9.130429
15,BLR,65.0,0.825,0.825,0.825,0.828,0.827,0.826,0.815,0.817,...,9.472708,9.487293,9.499064,9.495790,9.480031,9.435420,9.350944,9.251365,9.173237,9.115680
16,BEL,10.0,0.930,0.933,0.936,0.940,0.942,0.945,0.939,0.948,...,11.210119,11.275334,11.332700,11.376580,11.428605,11.490618,11.540107,11.570844,11.641820,11.712893
21,BIH,74.0,0.765,0.769,0.776,0.780,0.785,0.788,0.783,0.783,...,3.564829,3.518540,3.473003,3.428682,3.387000,3.345533,3.299349,3.244908,3.204802,3.185073
25,BGR,55.0,0.819,0.824,0.827,0.829,0.832,0.835,0.826,0.817,...,7.223450,7.177517,7.127434,7.075635,7.024745,6.975469,6.933652,6.877225,6.825864,6.795803
41,HRV,41.0,0.848,0.852,0.856,0.862,0.867,0.872,0.867,0.876,...,4.219479,4.183728,4.136444,4.079200,4.024868,3.986334,3.953958,3.924610,3.907027,3.896024
44,CZE,29.0,0.898,0.900,0.902,0.904,0.901,0.903,0.898,0.901,...,10.517226,10.524416,10.531948,10.541341,10.548937,10.554875,10.550130,10.530682,10.673213,10.809716
46,DNK,4.0,0.939,0.943,0.951,0.951,0.950,0.953,0.954,0.958,...,5.643794,5.683701,5.728201,5.765168,5.793825,5.814618,5.831530,5.856776,5.902903,5.948137
55,EST,36.0,0.885,0.888,0.890,0.894,0.897,0.901,0.901,0.899,...,1.314452,1.314576,1.315849,1.317424,1.321964,1.326822,1.329670,1.331749,1.350091,1.367196
59,FIN,12.0,0.936,0.938,0.940,0.942,0.945,0.947,0.947,0.949,...,5.461684,5.479717,5.495469,5.508396,5.515737,5.521759,5.529612,5.541075,5.569299,5.601185
60,FRA,26.0,0.900,0.901,0.905,0.908,0.911,0.914,0.909,0.915,...,64.692493,64.916336,65.086855,65.284776,65.519543,65.729459,65.905277,66.083547,66.277409,66.438822
64,DEU,5.0,0.949,0.948,0.949,0.951,0.952,0.957,0.955,0.958,...,81.376080,82.077551,82.760103,83.104007,83.368505,83.559186,83.628709,83.697082,84.086227,84.548231
66,GRC,34.0,0.886,0.888,0.884,0.887,0.893,0.896,0.896,0.897,...,10.893166,10.820903,10.775504,10.753533,10.730844,10.718576,10.699369,10.579561,10.412480,10.242909
75,HUN,46.0,0.848,0.847,0.851,0.853,0.857,0.861,0.857,0.852,...,9.862842,9.839211,9.810532,9.785604,9.774394,9.770347,9.749457,9.707850,9.684306,9.686464
76,ISL,1.0,0.954,0.956,0.959,0.962,0.966,0.969,0.965,0.967,...,0.327512,0.330952,0.335574,0.343531,0.352854,0.360700,0.366614,0.372644,0.380356,0.387557
81,IRL,11.0,0.921,0.931,0.936,0.941,0.944,0.947,0.948,0.946,...,4.658239,4.702487,4.753503,4.810261,4.872555,4.933491,4.982607,5.028425,5.110016,5.196630
83,ITA,29.0,0.890,0.889,0.894,0.897,0.902,0.906,0.899,0.908,...,60.664172,60.575316,60.478108,60.390318,60.277499,60.130136,59.912769,59.729350,59.619115,59.499453
95,LVA,41.0,0.854,0.859,0.864,0.870,0.875,0.880,0.879,0.871,...,1.994149,1.977867,1.959863,1.942594,1.927588,1.914263,1.901123,1.885587,1.881063,1.882396
101,LTU,39.0,0.866,0.869,0.875,0.885,0.889,0.894,0.888,0.887,...,2.933168,2.905764,2.869109,2.829312,2.802478,2.795058,2.795765,2.794487,2.816920,2.854099
102,LUX,25.0,0.924,0.913,0.916,0.913,0.915,0.916,0.916,0.918,...,0.556279,0.569536,0.583506,0.596495,0.608101,0.620163,0.630597,0.640274,0.653312,0.665098
108,MLT,24.0,0.886,0.892,0.891,0.901,0.908,0.910,0.903,0.914,...,0.434484,0.444981,0.455269,0.467902,0.484557,0.504015,0.518207,0.524377,0.528192,0.532956
114,MDA,86.0,0.762,0.759,0.763,0.769,0.772,0.775,0.770,0.773,...,3.342709,3.287164,3.237794,3.193497,3.153773,3.112562,3.069131,3.023779,3.039985,3.067070
124,NLD,8.0,0.939,0.940,0.941,0.945,0.947,0.950,0.945,0.951,...,17.030089,17.107433,17.204693,17.315370,17.421280,17.537507,17.636731,17.730563,17.904421,18.092524
129,MKD,68.0,0.788,0.795,0.800,0.807,0.814,0.805,0.783,0.781,...,1.997834,1.980366,1.961259,1.940878,1.919728,1.897641,1.872016,1.851107,1.840233,1.831802
130,NOR,2.0,0.956,0.959,0.962,0.965,0.966,0.967,0.969,0.969,...,5.137395,5.189771,5.235983,5.276802,5.311752,5.347730,5.379274,5.408091,5.456802,5.519167
140,POL,35.0,0.873,0.879,0.884,0.882,0.884,0.887,0.880,0.884,...,38.265113,38.266314,38.263265,38.254959,38.241070,38.225884,38.171012,38.040301,38.385739,38.762844
141,PRT,40.0,0.854,0.857,0.859,0.864,0.866,0.872,0.870,0.876,...,10.406199,10.370267,10.346372,10.330844,10.325353,10.343213,10.370519,10.390956,10.417072,10.430738
143,ROU,55.0,0.820,0.823,0.823,0.828,0.833,0.838,0.832,0.829,...,19.968174,19.871019,19.777051,19.689401,19.597872,19.501542,19.392469,19.248161,19.166773,19.118478
144,RUS,64.0,0.831,0.833,0.835,0.838,0.845,0.847,0.818,0.813,...,144.925638,145.307615,145.778677,146.186799,146.430146,146.533067,146.371298,145.836175,145.579899,145.440501
154,SRB,62.0,0.795,0.802,0.806,0.808,0.814,0.817,0.809,0.807,...,7.227202,7.177253,7.126083,7.073506,7.020019,6.966152,6.907812,6.835430,6.791213,6.773201
158,SVK,44.0,0.859,0.861,0.864,0.865,0.868,0.871,0.867,0.859,...,5.415230,5.420278,5.427259,5.435701,5.443232,5.450626,5.455024,5.442759,5.473197,5.518054
159,SVN,21.0,0.907,0.909,0.914,0.918,0.922,0.923,0.918,0.924,...,2.058400,2.059947,2.061373,2.062410,2.069481,2.083439,2.102419,2.113494,2.115228,2.118396
164,ESP,28.0,0.890,0.895,0.900,0.902,0.905,0.910,0.901,0.912,...,46.720188,46.683686,46.732771,46.868595,47.092821,47.435119,47.679489,47.735664,47.828382,47.911580
168,SWE,5.0,0.943,0.945,0.947,0.949,0.950,0.955,0.951,0.958,...,9.696433,9.799482,9.923280,10.057861,10.175405,10.279125,10.353687,10.416132,10.487338,10.551494
169,CHE,2.0,0.956,0.957,0.959,0.960,0.962,0.965,0.963,0.968,...,8.190236,8.283934,8.374901,8.453628,8.516345,8.577524,8.640581,8.707024,8.792182,8.870561
183,UKR,87.0,0.788,0.778,0.780,0.785,0.784,0.789,0.783,0.772,...,45.972380,45.784896,45.616832,45.436042,45.208907,44.957458,44.680014,44.298640,41.048766,37.732836
185,GBR,13.0,0.932,0.931,0.934,0.937,0.936,0.941,0.930,0.941,...,64.865916,65.382110,65.893358,66.354471,66.752475,67.110958,67.351861,67.668792,68.179316,68.682963

In [140]:
df_hdi_melted = pd.wide_to_long(df_hdi, stubnames=['hdi','le','eys','mys','gnipc'], i='iso3', j='Year', sep='_')

In [132]:
df_hdi_melted.head()

,,abr_2014,abr_2015,abr_2016,abr_2017,abr_2018,abr_2019,abr_2020,abr_2021,abr_2022,abr_2023,...,se_m_2019,se_m_2020,se_m_2021,se_m_2022,se_m_2023,hdi,le,eys,mys,gnipc
iso3,Year,,,,,,,,,,,,,,,,,,,,,
ALB,2014,21.767,20.656,18.518,16.778,15.456,14.949,14.004,13.002,12.827,12.789,...,92.677055,93.141407,93.605759,93.857521,93.857521,0.797,78.029,15.720370,10.00868,13019.67144
AUT,2014,7.784,7.848,7.505,6.897,5.715,5.290,4.907,4.426,4.205,3.836,...,99.057083,99.205521,99.026894,98.423279,98.683769,0.919,81.390,16.022249,12.01000,62502.99636
BLR,2014,21.116,18.336,16.076,13.395,11.932,11.351,10.911,10.659,9.903,8.595,...,99.029999,99.460558,99.892990,99.892990,99.892990,0.825,73.245,15.413680,11.66500,25819.62880
BEL,2014,7.153,6.659,6.228,5.905,5.528,5.204,4.884,4.609,4.372,3.670,...,89.709999,90.162140,90.726936,90.955208,90.955208,0.930,81.080,19.707769,11.64000,58998.64981
BIH,2014,10.289,10.818,11.300,11.613,11.814,11.354,11.311,11.192,11.089,11.217,...,91.669998,94.019997,95.109997,96.199997,96.199997,0.765,77.089,13.646000,9.19000,13742.35329

In [141]:
df_hdi_melted.reset_index(inplace=True)

In [142]:
df_hdi_melted = df_hdi_melted[['iso3', 'Year','hdi_rank_2023', 'hdi', 'le', 'eys', 'mys', 'gnipc']]

In [143]:
df_hdi_melted.head()

  iso3  Year  hdi_rank_2023    hdi      le        eys       mys        gnipc
0  ALB  2014           71.0  0.797  78.029  15.720370  10.00868  13019.67144
1  AUT  2014           22.0  0.919  81.390  16.022249  12.01000  62502.99636
2  BLR  2014           65.0  0.825  73.245  15.413680  11.66500  25819.62880
3  BEL  2014           10.0  0.930  81.080  19.707769  11.64000  58998.64981
4  BIH  2014           74.0  0.765  77.089  13.646000   9.19000  13742.35329

In [144]:
df_hdi_melted.rename(columns={'iso3': 'Country Code', 'hdi_rank_2023': 'HDI Rank', 'hdi': 'HDI', 'le': 'Life Expectancy', 'eys': 'Expected Years of Education', 'mys': 'Mean Years of Education', 'gnipc': 'Gross National Income per Capita'}, inplace=True)

In [145]:
df_hdi_melted.head()

,Country Code,Year,HDI Rank,HDI,Life Expectancy,Expected Years of Education,Mean Years of Education,Gross National Income per Capita
0,ALB,2014,71.0,0.797,78.029,15.720370,10.00868,13019.67144
1,AUT,2014,22.0,0.919,81.390,16.022249,12.01000,62502.99636
2,BLR,2014,65.0,0.825,73.245,15.413680,11.66500,25819.62880
3,BEL,2014,10.0,0.930,81.080,19.707769,11.64000,58998.64981
4,BIH,2014,74.0,0.765,77.089,13.646000,9.19000,13742.35329

In [146]:
skupno = pd.merge(skupno, df_hdi_melted, on=['Country Code', 'Year'], how='left')

In [147]:
skupno.head()

,Country,Country Code,Year,Rank,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,...,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,HDI Rank,HDI,Life Expectancy,Expected Years of Education,Mean Years of Education,Gross National Income per Capita
0,Switzerland,CHE,2014,1.0,207.35,137.55,70.00,68.00,143.20,7.05,...,NaN,NaN,NaN,NaN,2.0,0.956,83.084,16.089720,13.64,79041.54726
1,Germany,DEU,2014,2.0,189.65,109.05,71.90,76.00,86.95,5.85,...,NaN,NaN,NaN,NaN,5.0,0.949,80.906,17.118401,14.04,59865.51686
2,Sweden,SWE,2014,3.5,178.75,104.00,59.85,76.15,101.10,9.55,...,NaN,NaN,NaN,NaN,5.0,0.943,82.224,18.093519,12.29,58807.67134
3,Finland,FIN,2014,3.5,180.75,97.25,70.80,68.85,102.65,7.50,...,NaN,NaN,NaN,NaN,12.0,0.936,81.055,19.254250,12.60,53205.33544
4,Denmark,DNK,2014,5.0,172.10,96.15,71.80,84.10,115.00,6.15,...,NaN,NaN,NaN,NaN,4.0,0.939,80.632,19.208990,12.39,62951.49558

In [148]:
skupno_clean = skupno.dropna().copy()

In [149]:
skupno_clean.head()

,Country,Country Code,Year,Rank,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,...,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,HDI Rank,HDI,Life Expectancy,Expected Years of Education,Mean Years of Education,Gross National Income per Capita
161,Denmark,DNK,2019,1.0,197.55,112.55,75.55,79.30,82.65,7.20,...,0.665040,0.242793,0.495260,2.432741,4.0,0.953,81.434,18.620131,12.91,67926.47865
162,Switzerland,CHE,2019,2.0,196.00,128.75,78.65,72.95,121.95,9.35,...,0.628954,0.269056,0.407946,2.350267,2.0,0.965,83.780,16.344580,13.86,78234.45513
163,Finland,FIN,2019,3.0,194.55,110.55,77.25,74.40,72.50,7.95,...,0.662317,0.159670,0.477857,2.762835,12.0,0.947,81.864,19.043110,12.87,57744.73991
164,Austria,AUT,2019,4.5,189.45,93.30,77.70,79.35,71.95,10.35,...,0.603369,0.255510,0.281256,2.398446,22.0,0.928,81.907,16.076250,12.26,65534.68727
165,Netherlands,NLD,2019,5.5,187.65,100.25,71.45,76.70,75.00,7.45,...,0.613626,0.336318,0.368570,2.352117,8.0,0.950,82.053,18.373995,12.45,65792.10752

In [150]:
print(skupno_clean.columns.tolist())

['Country', 'Country Code', 'Year', 'Rank', 'Quality of Life Index', 'Purchasing Power Index', 'Safety Index', 'Health Care Index', 'Cost of Living Index', 'Property Price to Income Ratio', 'Traffic Commute Time Index', 'Pollution Index', 'Climate Index', 'Life evaluation (3-year average)', 'Explained by: Log GDP per capita', 'Explained by: Social support', 'Explained by: Healthy life expectancy', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Perceptions of corruption', 'Dystopia + residual', 'HDI Rank', 'HDI', 'Life Expectancy', 'Expected Years of Education', 'Mean Years of Education', 'Gross National Income per Capita']

In [151]:
df_final = skupno_clean.copy().drop(columns=['Country', 'Rank', 'HDI Rank'])